# Generated by Django 2.2.7 on 2020-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
