# Generated by Django 2.2.7 on 2020-07-19 13:04

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('DivarApp', '0002_auto_20200719_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('yazd', 'یزد'), ('tehran', 'تهران')], default='tehran', max_length=20, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='car',
            name='detail',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='car',
            name='function',
            field=models.IntegerField(default=0, verbose_name='کارکرد(کیلومتر)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_chatActive',
            field=models.BooleanField(default=True, verbose_name='آیا چت فعال باشد؟'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_exchange',
            field=models.BooleanField(default=False, verbose_name='قابل معاوضه'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_immediate',
            field=models.BooleanField(default=False, verbose_name='فوری'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [0, 0], 'marker_color': 'blue'}, null=True, verbose_name='نقشه'),
        ),
        migrations.AlterField(
            model_name='car',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='car',
            name='prod_year',
            field=models.PositiveSmallIntegerField(verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sell_choice',
            field=models.CharField(choices=[('sell', 'فروش'), ('rent', 'اجاره'), ('need', 'درخواستی')], default='sell', max_length=20, verbose_name='نوع فروش'),
        ),
        migrations.AlterField(
            model_name='car',
            name='zone',
            field=models.CharField(choices=[('AKB', 'اکباتان'), ('VALI', 'ولی عصر'), ('CHTGR', 'چیتگر'), ('AGHD', 'اقدسیه'), ('ARG', 'آرژانتین'), ('OTHER', 'حومه شهر'), ('KSHV', 'بلوارکشاورز')], default='OTHER', max_length=20, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('yazd', 'یزد'), ('tehran', 'تهران')], default='tehran', max_length=20, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='detail',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_chatActive',
            field=models.BooleanField(default=True, verbose_name='آیا چت فعال باشد؟'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_exchange',
            field=models.BooleanField(default=False, verbose_name='قابل معاوضه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_immediate',
            field=models.BooleanField(default=False, verbose_name='فوری'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [0, 0], 'marker_color': 'blue'}, null=True, verbose_name='نقشه'),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zone',
            field=models.CharField(choices=[('AKB', 'اکباتان'), ('VALI', 'ولی عصر'), ('CHTGR', 'چیتگر'), ('AGHD', 'اقدسیه'), ('ARG', 'آرژانتین'), ('OTHER', 'حومه شهر'), ('KSHV', 'بلوارکشاورز')], default='OTHER', max_length=20, verbose_name='منطقه'),
        ),
    ]
