# Generated by Django 2.2.7 on 2020-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivarApp', '0004_auto_20200723_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال اگهی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال اگهی'),
        ),
    ]
